In [1]:
import yfinance as fy

In [ ]:
data = fy.Ticker("AAPL",)
data.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 164000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 63,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 16520856,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 60,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5020737,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 60,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 57,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 52,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 50,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1748736000,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 201.0,
 'open': 201.895,
 'dayLow': 200.22,
 'dayHigh': 203.22,
 'regularMarketPreviousClose': 201.0,
 'regularMarketOpen': 201.895,
 'regularMarketDayLow': 200.22,
 'regularMarketDayHigh': 203.22,
 'dividendRate': 1.04,
 'dividendYield': 0.52,
 'exDividendDate': 1747008000,
 'payoutRatio': 0.1558,
 'fiveYearAvgDividendYield': 0.56,
 'beta': 1.211,
 'trailingPE': 31.369736,
 'forwardPE': 24.197351,
 'volume': 70534466,
 'regularMarketVolume': 70534466,
 'averageVolume': 62515124,
 'averageVolume10days': 54884960,
 'averageDailyVolume10Day': 54884960,
 'bid': 200.95,
 'ask': 201.46,
 'bidSize': 2,
 'askSize': 29,
 'marketCap': 3003290746880,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 260.1,
 'priceToSalesTrailing12Months': 7.501363,
 'fiftyDayAverage': 202.6222,
 'twoHundredDayAverage': 223.33345,
 'trailingAnnualDividendRate': 1.0,
 'trailingAnnualDividendYield': 0.0049751243,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3052983812096,
 'profitMargins': 0.24301,
 'floatShares': 14911480604,
 'sharesOutstanding': 14935799808,
 'sharesShort': 100226522,
 'sharesShortPriorMonth': 105169332,
 'sharesShortPreviousMonthDate': 1747267200,
 'dateShortInterest': 1749772800,
 'sharesPercentSharesOut': 0.0067000003,
 'heldPercentInsiders': 0.02085,
 'heldPercentInstitutions': 0.62901,
 'shortRatio': 1.91,
 'shortPercentOfFloat': 0.0067000003,
 'impliedSharesOutstanding': 14977399808,
 'bookValue': 4.471,
 'priceToBook': 44.974277,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1743206400,
 'earningsQuarterlyGrowth': 0.048,
 'netIncomeToCommon': 97294000128,
 'trailingEps': 6.41,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 7.625,
 'enterpriseToEbitda': 21.985,
 '52WeekChange': -0.07229525,
 'SandP52WeekChange': 0.12748289,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1747008000,
 'quoteType': 'EQUITY',
 'currentPrice': 201.08,
 'targetHighPrice': 300.0,
 'targetLowPrice': 170.62,
 'targetMeanPrice': 228.60326,
 'targetMedianPrice': 230.0,
 'recommendationMean': 2.1087,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 40,
 'totalCash': 48497999872,
 'totalCashPerShare': 3.247,
 'ebitda': 138865999872,
 'totalDebt': 98186002432,
 'quickRatio': 0.68,
 'currentRatio': 0.821,
 'totalRevenue': 400366010368,
 'debtToEquity': 146.994,
 'revenuePerShare': 26.455,
 'returnOnAssets': 0.23809999,
 'returnOnEquity': 1.38015,
 'grossProfits': 186699005952,
 'freeCashflow': 97251500032,
 'operatingCashflow': 109555998720,
 'earningsGrowth': 0.078,
 'revenueGrowth': 0.051,
 'grossMargins': 0.46632,
 'ebitdaMargins': 0.34685,
 'operatingMargins': 0.31028998,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'regularMarketChangePercent': 0.0398019,
 'regularMarketPrice': 201.08,
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1751068796,
 'regularMarketTime': 1751054402,
 'twoHundredDayAverageChange': -22.253448,
 'twoHundredDayAverageChangePercent': -0.099642254,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.1 - Buy',
 'cryptoTradeable': False,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.05435583,
 'postMarketPrice': 201.1893,
 'postMarketChange': 0.109298706,
 'regularMarketChange': 0.0800018,
 'regularMarketDayRange': '200.22 - 203.22',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 62515124,
 'fiftyTwoWeekLowChange': 31.869995,
 'fiftyTwoWeekLowChangePercent': 0.1883458,
 'fiftyTwoWeekRange': '169.21 - 260.1',
 'fiftyTwoWeekHighChange': -59.020004,
 'fiftyTwoWeekHighChangePercent': -0.22691274,
 'fiftyTwoWeekChangePercent': -7.2295246,
 'dividendDate': 1747267200,
 'earningsTimestamp': 1746131400,
 'earningsTimestampStart': 1753873140,
 'earningsTimestampEnd': 1754308800,
 'earningsCallTimestampStart': 1746133200,
 'earningsCallTimestampEnd': 1746133200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 6.41,
 'epsForward': 8.31,
 'epsCurrentYear': 7.18592,
 'priceEpsCurrentYear': 27.9825,
 'fiftyDayAverageChange': -1.5421906,
 'fiftyDayAverageChangePercent': -0.007611163,
 'displayName': 'Apple',
 'trailingPegRatio': 1.8326}

In [ ]:
data.calendar

{'Dividend Date': datetime.date(2025, 5, 15),
 'Ex-Dividend Date': datetime.date(2025, 5, 12),
 'Earnings Date': [datetime.date(2025, 7, 30), datetime.date(2025, 8, 4)],
 'Earnings High': 1.51,
 'Earnings Low': 1.34,
 'Earnings Average': 1.42415,
 'Revenue High': 90104000000,
 'Revenue Low': 86919000000,
 'Revenue Average': 88638880990}

In [5]:
data.analyst_price_targets

{'current': 201.08,
 'high': 300.0,
 'low': 170.62,
 'mean': 228.60326,
 'median': 230.0}

In [6]:
data.quarterly_incomestmt

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.155,0.147,0.21,0.159,0.158,NaN
Normalized EBITDA,32250000000.0,45912000000.0,32502000000.0,28202000000.0,30736000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Reconciled Depreciation,2661000000.0,3080000000.0,2911000000.0,2850000000.0,2836000000.0,NaN
Reconciled Cost Of Revenue,50492000000.0,66025000000.0,51051000000.0,46099000000.0,48482000000.0,NaN
EBITDA,32250000000.0,45912000000.0,32502000000.0,28202000000.0,30736000000.0,NaN
EBIT,29589000000.0,42832000000.0,29591000000.0,25352000000.0,27900000000.0,NaN
Net Interest Income,NaN,NaN,NaN,NaN,NaN,-18000000.0
Interest Expense,NaN,NaN,NaN,NaN,NaN,1002000000.0
Interest Income,NaN,NaN,NaN,NaN,NaN,984000000.0
Normalized Income,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Net Income From Continuing And Discontinued Operation,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Total Expenses,65770000000.0,81468000000.0,65339000000.0,60425000000.0,62853000000.0,NaN
Total Operating Income As Reported,29589000000.0,42832000000.0,29591000000.0,25352000000.0,27900000000.0,NaN
Diluted Average Shares,15056133000.0,15150865000.0,15242853000.0,15348175000.0,15464709000.0,NaN
Basic Average Shares,14994082000.0,15081724000.0,15171990000.0,15287521000.0,15405856000.0,NaN
Diluted EPS,1.65,2.4,0.97,1.4,1.53,NaN
Basic EPS,1.65,2.41,0.97,1.4,1.53,NaN
Diluted NI Availto Com Stockholders,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Net Income Common Stockholders,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Net Income,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Net Income Including Noncontrolling Interests,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Net Income Continuous Operations,24780000000.0,36330000000.0,14736000000.0,21448000000.0,23636000000.0,NaN
Tax Provision,4530000000.0,6254000000.0,14874000000.0,4046000000.0,4422000000.0,NaN
Pretax Income,29310000000.0,42584000000.0,29610000000.0,25494000000.0,28058000000.0,NaN
Other Income Expense,-279000000.0,-248000000.0,19000000.0,142000000.0,158000000.0,NaN
Other Non Operating Income Expenses,-279000000.0,-248000000.0,19000000.0,142000000.0,158000000.0,NaN
Net Non Operating Interest Income Expense,NaN,NaN,NaN,NaN,NaN,-18000000.0
Interest Expense Non Operating,NaN,NaN,NaN,NaN,NaN,1002000000.0
Interest Income Non Operating,NaN,NaN,NaN,NaN,NaN,984000000.0
Operating Income,29589000000.0,42832000000.0,29591000000.0,25352000000.0,27900000000.0,NaN
Operating Expense,15278000000.0,15443000000.0,14288000000.0,14326000000.0,14371000000.0,NaN
Research And Development,8550000000.0,8268000000.0,7765000000.0,8006000000.0,7903000000.0,NaN
Selling General And Administration,6728000000.0,7175000000.0,6523000000.0,6320000000.0,6468000000.0,NaN
Gross Profit,44867000000.0,58275000000.0,43879000000.0,39678000000.0,42271000000.0,NaN
Cost Of Revenue,50492000000.0,66025000000.0,51051000000.0,46099000000.0,48482000000.0,NaN
Total Revenue,95359000000.0,124300000000.0,94930000000.0,85777000000.0,90753000000.0,NaN
Operating Revenue,95359000000.0,124300000000.0,94930000000.0,85777000000.0,90753000000.0,NaN

In [ ]:
data.history(period="6mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-05-28 00:00:00-04:00,200.589996,202.729996,199.899994,200.419998,45339700,0.0,0.0
2025-05-29 00:00:00-04:00,203.580002,203.809998,198.509995,199.949997,51396800,0.0,0.0
2025-05-30 00:00:00-04:00,199.369995,201.960007,196.779999,200.850006,70819900,0.0,0.0
2025-06-02 00:00:00-04:00,200.279999,202.130005,200.119995,201.699997,35423300,0.0,0.0
2025-06-03 00:00:00-04:00,201.350006,203.770004,200.960007,203.270004,46381600,0.0,0.0
2025-06-04 00:00:00-04:00,202.910004,206.240005,202.100006,202.820007,43604000,0.0,0.0
2025-06-05 00:00:00-04:00,203.500000,204.750000,200.149994,200.630005,55126100,0.0,0.0
2025-06-06 00:00:00-04:00,203.000000,205.699997,202.050003,203.919998,46607700,0.0,0.0
2025-06-09 00:00:00-04:00,204.389999,206.000000,200.020004,201.449997,72862600,0.0,0.0
2025-06-10 00:00:00-04:00,200.600006,204.350006,200.570007,202.669998,54672600,0.0,0.0
2025-06-11 00:00:00-04:00,203.500000,204.500000,198.410004,198.779999,60989900,0.0,0.0
2025-06-12 00:00:00-04:00,199.080002,199.679993,197.360001,199.199997,43904600,0.0,0.0
2025-06-13 00:00:00-04:00,199.729996,200.369995,195.699997,196.449997,51447300,0.0,0.0
2025-06-16 00:00:00-04:00,197.300003,198.690002,196.559998,198.419998,43020700,0.0,0.0
2025-06-17 00:00:00-04:00,197.199997,198.389999,195.210007,195.639999,38856200,0.0,0.0
2025-06-18 00:00:00-04:00,195.940002,197.570007,195.070007,196.580002,45394700,0.0,0.0
2025-06-20 00:00:00-04:00,198.240005,201.699997,196.860001,201.000000,96813500,0.0,0.0
2025-06-23 00:00:00-04:00,201.630005,202.300003,198.960007,201.500000,55814300,0.0,0.0
2025-06-24 00:00:00-04:00,202.589996,203.440002,200.199997,200.300003,54064000,0.0,0.0
2025-06-25 00:00:00-04:00,201.449997,203.669998,200.619995,201.559998,39525700,0.0,0.0
2025-06-26 00:00:00-04:00,201.429993,202.639999,199.460007,201.000000,50799100,0.0,0.0
2025-06-27 00:00:00-04:00,201.889999,203.220001,200.000000,201.080002,73114100,0.0,0.0

In [ ]:
fy.download(['MSFT'],period="1mo")

C:\Users\Aman\AppData\Local\Temp\ipykernel_11892\2624757769.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  fy.download(['MSFT'],period="2mo")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-04-28  390.443207  392.020298  385.931501  391.241729  16579400
2025-04-29  393.317932  394.375987  389.664635  390.582932  14974000
2025-04-30  394.535706  395.933134  383.735526  389.584773  36461100
2025-05-01  424.620453  436.189211  424.121369  430.319981  58938100
2025-05-02  434.482361  438.634741  429.202046  430.948839  30757400
2025-05-05  435.370728  438.694612  431.318140  432.076757  20136100
2025-05-06  432.515961  436.927874  430.379898  431.408009  15104200
2025-05-07  432.555908  437.317156  430.319992  433.045001  23295300
2025-05-08  437.367065  442.856987  434.861655  437.127485  23491300
2025-05-09  437.926056  439.932352  435.081272  439.193718  15324200
2025-05-12  448.436737  448.546521  438.974098  445.122814  22821900
2025-05-13  448.316986  449.844181  444.543884  446.959462  23618800
2025-05-14  452.109985  453.068218  447.318794  447.318794  19902800
2025-05-15  453.130005  456.190002  450.429993  450.769989  21992300
2025-05-16  454.269989  454.359985  448.730011  452.049988  23849800
2025-05-19  458.869995  459.589996  450.799988  450.880005  21336500
2025-05-20  458.170013  458.339996  454.320007  455.589996  15441800
2025-05-21  452.570007  457.779999  451.809998  454.570007  19216900
2025-05-22  454.859985  460.250000  453.899994  454.950012  18025600
2025-05-23  450.179993  453.690002  448.910004  449.980011  16883500
2025-05-27  460.690002  460.950012  456.119995  456.480011  20974300
2025-05-28  457.359985  462.519989  456.929993  461.220001  17086300
2025-05-29  458.679993  461.720001  455.309998  461.549988  13974800
2025-05-30  460.359985  461.679993  455.540009  459.720001  34770500
2025-06-02  461.970001  462.109985  456.890015  457.140015  16626500
2025-06-03  462.970001  464.140015  460.859985  461.470001  15743800
2025-06-04  463.869995  465.690002  463.019989  464.000000  14162700
2025-06-05  467.679993  469.649994  464.029999  464.959991  20131700
2025-06-06  470.380005  473.339996  468.779999  470.089996  15285600
2025-06-09  472.750000  473.429993  468.619995  469.700012  16469900
2025-06-10  470.920013  472.799988  466.959991  471.190002  15375900
2025-06-11  472.619995  475.470001  469.660004  470.019989  16399200
2025-06-12  478.869995  480.420013  473.519989  475.019989  18950600
2025-06-13  474.959991  479.179993  472.760010  476.410004  16814500
2025-06-16  479.140015  480.690002  475.000000  475.209991  15626100
2025-06-17  478.040009  478.739990  474.079987  475.399994  15414100
2025-06-18  480.239990  481.000000  474.459991  478.000000  17526500
2025-06-20  477.399994  483.459991  476.869995  482.230011  37576200
2025-06-23  486.000000  487.750000  472.510010  478.209991  24864000
2025-06-24  490.109985  491.850006  486.799988  488.950012  22305600
2025-06-25  492.269989  494.559998  489.390015  492.040009  17495100
2025-06-26  497.450012  498.040009  492.809998  492.980011  21578900
2025-06-27  495.940002  499.299988  493.029999  497.549988  34532600